version: "3.8"
services:
  jupyter:
    build:
      dockerfile: ./dockerfile
      context: .
    volumes:
      - ./notebooks:/opt/notebooks
      - ./config:/root/.jupyter
    ports:
      - 8888:8888
